### ISSUE TITLE
pylon_camera-pkg does not support image encodings differing from mono8

### ISSUE THREAD

**Issue by marc-up** [magazino/pylon_camera#2]
Adding this feature is not planned in the close future.

If several people will vote for that issue, and one likes to make a pull request, I can imagine to give a developer introduction on how to add this feature in the code or rather on what parts should be changed.

**Comment by pylipp** [comment]
I'm interested in color camera support since I'm using a dart, too! 
Also I found out that RGB8 support has been implemented in [this fork](https://github.com/kmalhan/pylon_camera/tree/rgb8_support). I could run the node using a daA1920-30uc. 

EDIT: I just saw that there has already been PR #7 , so nvm.
